#!/bin/bash

bash /usr/lib/raspiwifi/reset_device/static_files/clean_firewall.sh &

python3 /usr/lib/raspiwifi/reset_device/reset.py &

python3 /usr/lib/raspiwifi/reset_device/connection_monitor.py &
