#!/bin/bash

bash /usr/lib/raspiwifi/reset_device/static_files/firewall.sh &

python3 /usr/lib/raspiwifi/reset_device/reset.py &

python3 /usr/lib/raspiwifi/configuration_app/app.py &

hostapd -dd /etc/hostapd/hostapd.conf &
